<?php

// Data functions (insert, update, delete, form) for table table1

// This script and data application were generated by AppGini 22.12
// Download AppGini for free from https://bigprof.com/appgini/download/

function table1_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('table1');
	if(!$arrPerm['insert']) return false;

	$data = [
		'field2' => Request::dateComponents('field2', ''),
		'field3' => Request::lookup('field3', ''),
		'field5' => Request::lookup('field5', ''),
		'field7' => Request::val('field7', '0.000'),
		'field8' => Request::val('field8', '0.000'),
		'field10' => Request::lookup('field10', ''),
		'field12' => Request::lookup('field12', ''),
		'field16' => Request::val('field16', ''),
		'field17' => Request::lookup('field17', ''),
		'field18' => Request::val('field18', ''),
		'field19' => Request::val('field19', ''),
		'field21' => Request::lookup('field21', ''),
		'field23' => Request::val('field23', ''),
		'field26' => Request::val('field26', ''),
		'field29' => Request::val('field29', ''),
		'field27' => Request::lookup('field27', ''),
		'field15' => br2nl(Request::val('field15', '')),
	];

	if($data['field2'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#1578;&#1575;&#1585;&#1610;&#1582; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['field3'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#1606;&#1608;&#1593; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: table1_before_insert
	if(function_exists('table1_before_insert')) {
		$args = [];
		if(!table1_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('table1', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	update_calc_fields('table1', $recID, calculated_fields()['table1']);

	// hook: table1_after_insert
	if(function_exists('table1_after_insert')) {
		$res = sql("SELECT * FROM `table1` WHERE `ID`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!table1_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('table1', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) table1_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function table1_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function table1_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('table1', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: table1_before_delete
	if(function_exists('table1_before_delete')) {
		$args = [];
		if(!table1_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `table1` WHERE `ID`='{$selected_id}'", $eo);

	// hook: table1_after_delete
	if(function_exists('table1_after_delete')) {
		$args = [];
		table1_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='table1' AND `pkValue`='{$selected_id}'", $eo);
}

function table1_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('table1', $selected_id, 'edit')) return false;

	$data = [
		'field2' => Request::dateComponents('field2', ''),
		'field3' => Request::lookup('field3', ''),
		'field5' => Request::lookup('field5', ''),
		'field7' => Request::val('field7', ''),
		'field8' => Request::val('field8', ''),
		'field10' => Request::lookup('field10', ''),
		'field12' => Request::lookup('field12', ''),
		'field16' => Request::val('field16', ''),
		'field17' => Request::lookup('field17', ''),
		'field18' => Request::val('field18', ''),
		'field19' => Request::val('field19', ''),
		'field21' => Request::lookup('field21', ''),
		'field23' => Request::val('field23', ''),
		'field26' => Request::val('field26', ''),
		'field29' => Request::val('field29', ''),
		'field27' => Request::lookup('field27', ''),
		'field15' => br2nl(Request::val('field15', '')),
	];

	if($data['field2'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#1578;&#1575;&#1585;&#1610;&#1582; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['field3'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} '&#1606;&#1608;&#1593; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577;': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('table1', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: table1_before_update
	if(function_exists('table1_before_update')) {
		$args = ['old_data' => $old_data];
		if(!table1_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'table1', 
		backtick_keys_once($set), 
		['`ID`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="table1_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('table1', $data['selectedID'], calculated_fields()['table1']);

	// hook: table1_after_update
	if(function_exists('table1_after_update')) {
		$res = sql("SELECT * FROM `table1` WHERE `ID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['ID'];
		$args = ['old_data' => $old_data];
		if(!table1_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='table1' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function table1_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	// mm: get table permissions
	$arrPerm = getTablePermissions('table1');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_field3 = Request::val('filterer_field3');
	$filterer_field5 = Request::val('filterer_field5');
	$filterer_field10 = Request::val('filterer_field10');
	$filterer_field12 = Request::val('filterer_field12');
	$filterer_field17 = Request::val('filterer_field17');
	$filterer_field21 = Request::val('filterer_field21');
	$filterer_field27 = Request::val('filterer_field27');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: field2
	$combo_field2 = new DateCombo;
	$combo_field2->DateFormat = "ymd";
	$combo_field2->MinYear = defined('table1.field2.MinYear') ? constant('table1.field2.MinYear') : 1900;
	$combo_field2->MaxYear = defined('table1.field2.MaxYear') ? constant('table1.field2.MaxYear') : 2100;
	$combo_field2->DefaultDate = parseMySQLDate('', '');
	$combo_field2->MonthNames = $Translation['month names'];
	$combo_field2->NamePrefix = 'field2';
	// combobox: field3
	$combo_field3 = new DataCombo;
	// combobox: field5
	$combo_field5 = new DataCombo;
	// combobox: field10
	$combo_field10 = new DataCombo;
	// combobox: field12
	$combo_field12 = new DataCombo;
	// combobox: field17
	$combo_field17 = new DataCombo;
	// combobox: field21
	$combo_field21 = new DataCombo;
	// combobox: field27
	$combo_field27 = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='table1' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='table1' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `table1` WHERE `ID`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'table1_view.php', false);
		}
		$combo_field2->DefaultDate = $row['field2'];
		$combo_field3->SelectedData = $row['field3'];
		$combo_field5->SelectedData = $row['field5'];
		$combo_field10->SelectedData = $row['field10'];
		$combo_field12->SelectedData = $row['field12'];
		$combo_field17->SelectedData = $row['field17'];
		$combo_field21->SelectedData = $row['field21'];
		$combo_field27->SelectedData = $row['field27'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_field3->SelectedData = $filterer_field3;
		$combo_field5->SelectedData = $filterer_field5;
		$combo_field10->SelectedData = $filterer_field10;
		$combo_field12->SelectedData = $filterer_field12;
		$combo_field17->SelectedData = $filterer_field17;
		$combo_field21->SelectedData = $filterer_field21;
		$combo_field27->SelectedData = $filterer_field27;
	}
	$combo_field3->HTML = '<span id="field3-container' . $rnd1 . '"></span><input type="hidden" name="field3" id="field3' . $rnd1 . '" value="' . html_attr($combo_field3->SelectedData) . '">';
	$combo_field3->MatchText = '<span id="field3-container-readonly' . $rnd1 . '"></span><input type="hidden" name="field3" id="field3' . $rnd1 . '" value="' . html_attr($combo_field3->SelectedData) . '">';
	$combo_field5->HTML = '<span id="field5-container' . $rnd1 . '"></span><input type="hidden" name="field5" id="field5' . $rnd1 . '" value="' . html_attr($combo_field5->SelectedData) . '">';
	$combo_field5->MatchText = '<span id="field5-container-readonly' . $rnd1 . '"></span><input type="hidden" name="field5" id="field5' . $rnd1 . '" value="' . html_attr($combo_field5->SelectedData) . '">';
	$combo_field10->HTML = '<span id="field10-container' . $rnd1 . '"></span><input type="hidden" name="field10" id="field10' . $rnd1 . '" value="' . html_attr($combo_field10->SelectedData) . '">';
	$combo_field10->MatchText = '<span id="field10-container-readonly' . $rnd1 . '"></span><input type="hidden" name="field10" id="field10' . $rnd1 . '" value="' . html_attr($combo_field10->SelectedData) . '">';
	$combo_field12->HTML = '<span id="field12-container' . $rnd1 . '"></span><input type="hidden" name="field12" id="field12' . $rnd1 . '" value="' . html_attr($combo_field12->SelectedData) . '">';
	$combo_field12->MatchText = '<span id="field12-container-readonly' . $rnd1 . '"></span><input type="hidden" name="field12" id="field12' . $rnd1 . '" value="' . html_attr($combo_field12->SelectedData) . '">';
	$combo_field17->HTML = '<span id="field17-container' . $rnd1 . '"></span><input type="hidden" name="field17" id="field17' . $rnd1 . '" value="' . html_attr($combo_field17->SelectedData) . '">';
	$combo_field17->MatchText = '<span id="field17-container-readonly' . $rnd1 . '"></span><input type="hidden" name="field17" id="field17' . $rnd1 . '" value="' . html_attr($combo_field17->SelectedData) . '">';
	$combo_field21->HTML = '<span id="field21-container' . $rnd1 . '"></span><input type="hidden" name="field21" id="field21' . $rnd1 . '" value="' . html_attr($combo_field21->SelectedData) . '">';
	$combo_field21->MatchText = '<span id="field21-container-readonly' . $rnd1 . '"></span><input type="hidden" name="field21" id="field21' . $rnd1 . '" value="' . html_attr($combo_field21->SelectedData) . '">';
	$combo_field27->HTML = '<span id="field27-container' . $rnd1 . '"></span><input type="hidden" name="field27" id="field27' . $rnd1 . '" value="' . html_attr($combo_field27->SelectedData) . '">';
	$combo_field27->MatchText = '<span id="field27-container-readonly' . $rnd1 . '"></span><input type="hidden" name="field27" id="field27' . $rnd1 . '" value="' . html_attr($combo_field27->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_field3__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['field3'] : htmlspecialchars($filterer_field3, ENT_QUOTES)); ?>"};
		AppGini.current_field5__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['field5'] : htmlspecialchars($filterer_field5, ENT_QUOTES)); ?>"};
		AppGini.current_field10__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['field10'] : htmlspecialchars($filterer_field10, ENT_QUOTES)); ?>"};
		AppGini.current_field12__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['field12'] : htmlspecialchars($filterer_field12, ENT_QUOTES)); ?>"};
		AppGini.current_field17__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['field17'] : htmlspecialchars($filterer_field17, ENT_QUOTES)); ?>"};
		AppGini.current_field21__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['field21'] : htmlspecialchars($filterer_field21, ENT_QUOTES)); ?>"};
		AppGini.current_field27__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['field27'] : htmlspecialchars($filterer_field27, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(field3_reload__RAND__) == 'function') field3_reload__RAND__();
				if(typeof(field5_reload__RAND__) == 'function') field5_reload__RAND__();
				if(typeof(field10_reload__RAND__) == 'function') field10_reload__RAND__();
				if(typeof(field12_reload__RAND__) == 'function') field12_reload__RAND__();
				if(typeof(field17_reload__RAND__) == 'function') field17_reload__RAND__();
				if(typeof(field21_reload__RAND__) == 'function') field21_reload__RAND__();
				if(typeof(field27_reload__RAND__) == 'function') field27_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function field3_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#field3-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_field3__RAND__.value, t: 'table1', f: 'field3' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="field3"]').val(resp.results[0].id);
							$j('[id=field3-container-readonly__RAND__]').html('<span class="match-text" id="field3-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table3_view_parent]').hide(); } else { $j('.btn[id=table3_view_parent]').show(); }


							if(typeof(field3_update_autofills__RAND__) == 'function') field3_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'table1', f: 'field3' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_field3__RAND__.value = e.added.id;
				AppGini.current_field3__RAND__.text = e.added.text;
				$j('[name="field3"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table3_view_parent]').hide(); } else { $j('.btn[id=table3_view_parent]').show(); }


				if(typeof(field3_update_autofills__RAND__) == 'function') field3_update_autofills__RAND__();
			});

			if(!$j("#field3-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_field3__RAND__.value, t: 'table1', f: 'field3' },
					success: function(resp) {
						$j('[name="field3"]').val(resp.results[0].id);
						$j('[id=field3-container-readonly__RAND__]').html('<span class="match-text" id="field3-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table3_view_parent]').hide(); } else { $j('.btn[id=table3_view_parent]').show(); }

						if(typeof(field3_update_autofills__RAND__) == 'function') field3_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_field3__RAND__.value, t: 'table1', f: 'field3' },
				success: function(resp) {
					$j('[id=field3-container__RAND__], [id=field3-container-readonly__RAND__]').html('<span class="match-text" id="field3-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table3_view_parent]').hide(); } else { $j('.btn[id=table3_view_parent]').show(); }

					if(typeof(field3_update_autofills__RAND__) == 'function') field3_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function field5_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#field5-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_field5__RAND__.value, t: 'table1', f: 'field5' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="field5"]').val(resp.results[0].id);
							$j('[id=field5-container-readonly__RAND__]').html('<span class="match-text" id="field5-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table2_view_parent]').hide(); } else { $j('.btn[id=table2_view_parent]').show(); }


							if(typeof(field5_update_autofills__RAND__) == 'function') field5_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'table1', f: 'field5' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_field5__RAND__.value = e.added.id;
				AppGini.current_field5__RAND__.text = e.added.text;
				$j('[name="field5"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table2_view_parent]').hide(); } else { $j('.btn[id=table2_view_parent]').show(); }


				if(typeof(field5_update_autofills__RAND__) == 'function') field5_update_autofills__RAND__();
			});

			if(!$j("#field5-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_field5__RAND__.value, t: 'table1', f: 'field5' },
					success: function(resp) {
						$j('[name="field5"]').val(resp.results[0].id);
						$j('[id=field5-container-readonly__RAND__]').html('<span class="match-text" id="field5-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table2_view_parent]').hide(); } else { $j('.btn[id=table2_view_parent]').show(); }

						if(typeof(field5_update_autofills__RAND__) == 'function') field5_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_field5__RAND__.value, t: 'table1', f: 'field5' },
				success: function(resp) {
					$j('[id=field5-container__RAND__], [id=field5-container-readonly__RAND__]').html('<span class="match-text" id="field5-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table2_view_parent]').hide(); } else { $j('.btn[id=table2_view_parent]').show(); }

					if(typeof(field5_update_autofills__RAND__) == 'function') field5_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function field10_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#field10-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_field10__RAND__.value, t: 'table1', f: 'field10' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="field10"]').val(resp.results[0].id);
							$j('[id=field10-container-readonly__RAND__]').html('<span class="match-text" id="field10-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }


							if(typeof(field10_update_autofills__RAND__) == 'function') field10_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'table1', f: 'field10' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_field10__RAND__.value = e.added.id;
				AppGini.current_field10__RAND__.text = e.added.text;
				$j('[name="field10"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }


				if(typeof(field10_update_autofills__RAND__) == 'function') field10_update_autofills__RAND__();
			});

			if(!$j("#field10-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_field10__RAND__.value, t: 'table1', f: 'field10' },
					success: function(resp) {
						$j('[name="field10"]').val(resp.results[0].id);
						$j('[id=field10-container-readonly__RAND__]').html('<span class="match-text" id="field10-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }

						if(typeof(field10_update_autofills__RAND__) == 'function') field10_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_field10__RAND__.value, t: 'table1', f: 'field10' },
				success: function(resp) {
					$j('[id=field10-container__RAND__], [id=field10-container-readonly__RAND__]').html('<span class="match-text" id="field10-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }

					if(typeof(field10_update_autofills__RAND__) == 'function') field10_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function field12_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#field12-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_field12__RAND__.value, t: 'table1', f: 'field12' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="field12"]').val(resp.results[0].id);
							$j('[id=field12-container-readonly__RAND__]').html('<span class="match-text" id="field12-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }


							if(typeof(field12_update_autofills__RAND__) == 'function') field12_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'table1', f: 'field12' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_field12__RAND__.value = e.added.id;
				AppGini.current_field12__RAND__.text = e.added.text;
				$j('[name="field12"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }


				if(typeof(field12_update_autofills__RAND__) == 'function') field12_update_autofills__RAND__();
			});

			if(!$j("#field12-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_field12__RAND__.value, t: 'table1', f: 'field12' },
					success: function(resp) {
						$j('[name="field12"]').val(resp.results[0].id);
						$j('[id=field12-container-readonly__RAND__]').html('<span class="match-text" id="field12-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }

						if(typeof(field12_update_autofills__RAND__) == 'function') field12_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_field12__RAND__.value, t: 'table1', f: 'field12' },
				success: function(resp) {
					$j('[id=field12-container__RAND__], [id=field12-container-readonly__RAND__]').html('<span class="match-text" id="field12-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }

					if(typeof(field12_update_autofills__RAND__) == 'function') field12_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function field17_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#field17-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_field17__RAND__.value, t: 'table1', f: 'field17' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="field17"]').val(resp.results[0].id);
							$j('[id=field17-container-readonly__RAND__]').html('<span class="match-text" id="field17-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table5_view_parent]').hide(); } else { $j('.btn[id=table5_view_parent]').show(); }


							if(typeof(field17_update_autofills__RAND__) == 'function') field17_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'table1', f: 'field17' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_field17__RAND__.value = e.added.id;
				AppGini.current_field17__RAND__.text = e.added.text;
				$j('[name="field17"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table5_view_parent]').hide(); } else { $j('.btn[id=table5_view_parent]').show(); }


				if(typeof(field17_update_autofills__RAND__) == 'function') field17_update_autofills__RAND__();
			});

			if(!$j("#field17-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_field17__RAND__.value, t: 'table1', f: 'field17' },
					success: function(resp) {
						$j('[name="field17"]').val(resp.results[0].id);
						$j('[id=field17-container-readonly__RAND__]').html('<span class="match-text" id="field17-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table5_view_parent]').hide(); } else { $j('.btn[id=table5_view_parent]').show(); }

						if(typeof(field17_update_autofills__RAND__) == 'function') field17_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_field17__RAND__.value, t: 'table1', f: 'field17' },
				success: function(resp) {
					$j('[id=field17-container__RAND__], [id=field17-container-readonly__RAND__]').html('<span class="match-text" id="field17-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table5_view_parent]').hide(); } else { $j('.btn[id=table5_view_parent]').show(); }

					if(typeof(field17_update_autofills__RAND__) == 'function') field17_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function field21_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#field21-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_field21__RAND__.value, t: 'table1', f: 'field21' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="field21"]').val(resp.results[0].id);
							$j('[id=field21-container-readonly__RAND__]').html('<span class="match-text" id="field21-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }


							if(typeof(field21_update_autofills__RAND__) == 'function') field21_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'table1', f: 'field21' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_field21__RAND__.value = e.added.id;
				AppGini.current_field21__RAND__.text = e.added.text;
				$j('[name="field21"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }


				if(typeof(field21_update_autofills__RAND__) == 'function') field21_update_autofills__RAND__();
			});

			if(!$j("#field21-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_field21__RAND__.value, t: 'table1', f: 'field21' },
					success: function(resp) {
						$j('[name="field21"]').val(resp.results[0].id);
						$j('[id=field21-container-readonly__RAND__]').html('<span class="match-text" id="field21-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }

						if(typeof(field21_update_autofills__RAND__) == 'function') field21_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_field21__RAND__.value, t: 'table1', f: 'field21' },
				success: function(resp) {
					$j('[id=field21-container__RAND__], [id=field21-container-readonly__RAND__]').html('<span class="match-text" id="field21-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }

					if(typeof(field21_update_autofills__RAND__) == 'function') field21_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function field27_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#field27-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_field27__RAND__.value, t: 'table1', f: 'field27' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="field27"]').val(resp.results[0].id);
							$j('[id=field27-container-readonly__RAND__]').html('<span class="match-text" id="field27-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }


							if(typeof(field27_update_autofills__RAND__) == 'function') field27_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'table1', f: 'field27' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_field27__RAND__.value = e.added.id;
				AppGini.current_field27__RAND__.text = e.added.text;
				$j('[name="field27"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }


				if(typeof(field27_update_autofills__RAND__) == 'function') field27_update_autofills__RAND__();
			});

			if(!$j("#field27-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_field27__RAND__.value, t: 'table1', f: 'field27' },
					success: function(resp) {
						$j('[name="field27"]').val(resp.results[0].id);
						$j('[id=field27-container-readonly__RAND__]').html('<span class="match-text" id="field27-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }

						if(typeof(field27_update_autofills__RAND__) == 'function') field27_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_field27__RAND__.value, t: 'table1', f: 'field27' },
				success: function(resp) {
					$j('[id=field27-container__RAND__], [id=field27-container-readonly__RAND__]').html('<span class="match-text" id="field27-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table4_view_parent]').hide(); } else { $j('.btn[id=table4_view_parent]').show(); }

					if(typeof(field27_update_autofills__RAND__) == 'function') field27_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/table1_templateDV.html';
	$templateCode = @file_get_contents($template_file);

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return table1_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return table1_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return table1_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($separateDV ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#field2').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#field2Day, #field2Month, #field2Year').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#field3').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#field3_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#field5').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#field5_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#field7').replaceWith('<div class=\"form-control-static\" id=\"field7\">' + (jQuery('#field7').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#field8').replaceWith('<div class=\"form-control-static\" id=\"field8\">' + (jQuery('#field8').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#field10').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#field10_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#field12').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#field12_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#field16').replaceWith('<div class=\"form-control-static\" id=\"field16\">' + (jQuery('#field16').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#field17').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#field17_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#field18').replaceWith('<div class=\"form-control-static\" id=\"field18\">' + (jQuery('#field18').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#field19').replaceWith('<div class=\"form-control-static\" id=\"field19\">' + (jQuery('#field19').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#field21').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#field21_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#field23').replaceWith('<div class=\"form-control-static\" id=\"field23\">' + (jQuery('#field23').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#field26').replaceWith('<div class=\"form-control-static\" id=\"field26\">' + (jQuery('#field26').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#field29').replaceWith('<div class=\"form-control-static\" id=\"field29\">' + (jQuery('#field29').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#field27').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#field27_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#field15').replaceWith('<div class=\"form-control-static\" id=\"field15\">' + (jQuery('#field15').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(field2)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_field2->GetHTML(true) . '</div>' : $combo_field2->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(field2)%%>', $combo_field2->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(field3)%%>', $combo_field3->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(field3)%%>', $combo_field3->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(field3)%%>', urlencode($combo_field3->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(field5)%%>', $combo_field5->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(field5)%%>', $combo_field5->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(field5)%%>', urlencode($combo_field5->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(field10)%%>', $combo_field10->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(field10)%%>', $combo_field10->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(field10)%%>', urlencode($combo_field10->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(field12)%%>', $combo_field12->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(field12)%%>', $combo_field12->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(field12)%%>', urlencode($combo_field12->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(field17)%%>', $combo_field17->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(field17)%%>', $combo_field17->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(field17)%%>', urlencode($combo_field17->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(field21)%%>', $combo_field21->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(field21)%%>', $combo_field21->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(field21)%%>', urlencode($combo_field21->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(field27)%%>', $combo_field27->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(field27)%%>', $combo_field27->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(field27)%%>', urlencode($combo_field27->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['field3' => ['table3', '&#1606;&#1608;&#1593; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577;'], 'field5' => ['table2', '&#1606;&#1608;&#1593; &#1575;&#1604;&#1593;&#1605;&#1604;&#1577;'], 'field10' => ['table4', '&#1605;&#1606; &#1582;&#1586;&#1610;&#1606;&#1577;'], 'field12' => ['table4', '&#1575;&#1604;&#1610; &#1582;&#1586;&#1610;&#1606;&#1577;'], 'field17' => ['table5', '&#1571;&#1587;&#1605; &#1575;&#1604;&#1593;&#1605;&#1610;&#1604;'], 'field21' => ['table4', '&#1575;&#1604;&#1605;&#1603;&#1610;&#1606;&#1577;'], 'field27' => ['table4', '&#1605;&#1606;.&#1582;&#1586;&#1610;&#1606;&#1577;'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(ID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field4)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field5)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field6)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field7)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field14)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field8)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field9)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field10)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field11)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field12)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field13)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field16)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field17)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field24)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field18)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field19)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field20)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field21)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field25)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field23)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field22)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field26)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field29)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field27)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field28)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field15)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', safe_html($urow['ID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', html_attr($row['ID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode($urow['ID']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field2)%%>', app_datetime($row['field2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field2)%%>', urlencode(app_datetime($urow['field2'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field3)%%>', safe_html($urow['field3']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field3)%%>', html_attr($row['field3']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field3)%%>', urlencode($urow['field3']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field4)%%>', safe_html($urow['field4']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field4)%%>', urlencode($urow['field4']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field5)%%>', safe_html($urow['field5']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field5)%%>', html_attr($row['field5']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field5)%%>', urlencode($urow['field5']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field6)%%>', safe_html($urow['field6']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field6)%%>', urlencode($urow['field6']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field7)%%>', safe_html($urow['field7']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field7)%%>', html_attr($row['field7']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field7)%%>', urlencode($urow['field7']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field14)%%>', safe_html($urow['field14']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field14)%%>', urlencode($urow['field14']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field8)%%>', safe_html($urow['field8']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field8)%%>', html_attr($row['field8']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field8)%%>', urlencode($urow['field8']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field9)%%>', safe_html($urow['field9']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field9)%%>', urlencode($urow['field9']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field10)%%>', safe_html($urow['field10']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field10)%%>', html_attr($row['field10']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field10)%%>', urlencode($urow['field10']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field11)%%>', safe_html($urow['field11']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field11)%%>', urlencode($urow['field11']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field12)%%>', safe_html($urow['field12']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field12)%%>', html_attr($row['field12']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field12)%%>', urlencode($urow['field12']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field13)%%>', safe_html($urow['field13']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field13)%%>', urlencode($urow['field13']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field16)%%>', safe_html($urow['field16']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field16)%%>', html_attr($row['field16']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field16)%%>', urlencode($urow['field16']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field17)%%>', safe_html($urow['field17']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field17)%%>', html_attr($row['field17']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field17)%%>', urlencode($urow['field17']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field24)%%>', safe_html($urow['field24']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field24)%%>', urlencode($urow['field24']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field18)%%>', safe_html($urow['field18']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field18)%%>', html_attr($row['field18']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field18)%%>', urlencode($urow['field18']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field19)%%>', safe_html($urow['field19']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field19)%%>', html_attr($row['field19']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field19)%%>', urlencode($urow['field19']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field20)%%>', safe_html($urow['field20']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field20)%%>', urlencode($urow['field20']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field21)%%>', safe_html($urow['field21']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field21)%%>', html_attr($row['field21']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field21)%%>', urlencode($urow['field21']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field25)%%>', safe_html($urow['field25']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field25)%%>', urlencode($urow['field25']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field23)%%>', safe_html($urow['field23']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field23)%%>', html_attr($row['field23']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field23)%%>', urlencode($urow['field23']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field22)%%>', safe_html($urow['field22']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field22)%%>', urlencode($urow['field22']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field26)%%>', safe_html($urow['field26']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field26)%%>', html_attr($row['field26']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field26)%%>', urlencode($urow['field26']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field29)%%>', safe_html($urow['field29']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field29)%%>', html_attr($row['field29']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field29)%%>', urlencode($urow['field29']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field27)%%>', safe_html($urow['field27']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field27)%%>', html_attr($row['field27']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field27)%%>', urlencode($urow['field27']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field28)%%>', safe_html($urow['field28']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field28)%%>', urlencode($urow['field28']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(field15)%%>', safe_html($urow['field15']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(field15)%%>', safe_html($urow['field15'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(field15)%%>', urlencode($urow['field15']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(ID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field3)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field4)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field4)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field5)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field5)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field6)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field6)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field7)%%>', '0.000', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field7)%%>', urlencode('0.000'), $templateCode);
		$templateCode = str_replace('<%%VALUE(field14)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field14)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field8)%%>', '0.000', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field8)%%>', urlencode('0.000'), $templateCode);
		$templateCode = str_replace('<%%VALUE(field9)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field9)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field10)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field10)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field11)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field11)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field12)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field12)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field13)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field13)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field16)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field16)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field17)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field17)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field24)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field24)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field18)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field18)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field19)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field19)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field20)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field20)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field21)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field21)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field25)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field25)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field23)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field23)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field22)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field22)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field26)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field26)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field29)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field29)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field27)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field27)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field28)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field28)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field15)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field15)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('table1');
	if($selected_id) {
		$jdata = get_joined_record('table1', $selected_id);
		if($jdata === false) $jdata = get_defaults('table1');
		$rdata = $row;
	}
	$templateCode .= loadView('table1-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: table1_dv
	if(function_exists('table1_dv')) {
		$args=[];
		table1_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}