<?php

// Data functions (insert, update, delete, form) for table table4

// This script and data application were generated by AppGini 22.12
// Download AppGini for free from https://bigprof.com/appgini/download/

function table4_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('table4');
	if(!$arrPerm['insert']) return false;

	$data = [
		'field2' => Request::val('field2', ''),
		'field3' => Request::lookup('field3', ''),
		'field4' => Request::lookup('field4', ''),
		'field19' => Request::lookup('field19', ''),
	];


	// hook: table4_before_insert
	if(function_exists('table4_before_insert')) {
		$args = [];
		if(!table4_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('table4', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	update_calc_fields('table4', $recID, calculated_fields()['table4']);

	// hook: table4_after_insert
	if(function_exists('table4_after_insert')) {
		$res = sql("SELECT * FROM `table4` WHERE `ID`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!table4_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('table4', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) table4_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function table4_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function table4_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('table4', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: table4_before_delete
	if(function_exists('table4_before_delete')) {
		$args = [];
		if(!table4_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: table1
	$res = sql("SELECT `ID` FROM `table4` WHERE `ID`='{$selected_id}'", $eo);
	$ID = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `table1` WHERE `field10`='" . makeSafe($ID[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'table1', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'table1', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'table4_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'table4_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: table1
	$res = sql("SELECT `ID` FROM `table4` WHERE `ID`='{$selected_id}'", $eo);
	$ID = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `table1` WHERE `field12`='" . makeSafe($ID[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'table1', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'table1', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'table4_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'table4_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: table1
	$res = sql("SELECT `ID` FROM `table4` WHERE `ID`='{$selected_id}'", $eo);
	$ID = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `table1` WHERE `field21`='" . makeSafe($ID[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'table1', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'table1', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'table4_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'table4_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	// child table: table1
	$res = sql("SELECT `ID` FROM `table4` WHERE `ID`='{$selected_id}'", $eo);
	$ID = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `table1` WHERE `field27`='" . makeSafe($ID[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'table1', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'table1', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'table4_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'table4_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `table4` WHERE `ID`='{$selected_id}'", $eo);

	// hook: table4_after_delete
	if(function_exists('table4_after_delete')) {
		$args = [];
		table4_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='table4' AND `pkValue`='{$selected_id}'", $eo);
}

function table4_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('table4', $selected_id, 'edit')) return false;

	$data = [
		'field2' => Request::val('field2', ''),
		'field3' => Request::lookup('field3', ''),
		'field4' => Request::lookup('field4', ''),
		'field19' => Request::lookup('field19', ''),
	];

	// get existing values
	$old_data = getRecord('table4', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: table4_before_update
	if(function_exists('table4_before_update')) {
		$args = ['old_data' => $old_data];
		if(!table4_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'table4', 
		backtick_keys_once($set), 
		['`ID`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="table4_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('table4', $data['selectedID'], calculated_fields()['table4']);

	// hook: table4_after_update
	if(function_exists('table4_after_update')) {
		$res = sql("SELECT * FROM `table4` WHERE `ID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['ID'];
		$args = ['old_data' => $old_data];
		if(!table4_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='table4' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function table4_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	// mm: get table permissions
	$arrPerm = getTablePermissions('table4');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_field3 = Request::val('filterer_field3');
	$filterer_field4 = Request::val('filterer_field4');
	$filterer_field19 = Request::val('filterer_field19');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: field3
	$combo_field3 = new DataCombo;
	// combobox: field4
	$combo_field4 = new DataCombo;
	// combobox: field19
	$combo_field19 = new DataCombo;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='table4' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='table4' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `table4` WHERE `ID`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'table4_view.php', false);
		}
		$combo_field3->SelectedData = $row['field3'];
		$combo_field4->SelectedData = $row['field4'];
		$combo_field19->SelectedData = $row['field19'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_field3->SelectedData = $filterer_field3;
		$combo_field4->SelectedData = $filterer_field4;
		$combo_field19->SelectedData = $filterer_field19;
	}
	$combo_field3->HTML = '<span id="field3-container' . $rnd1 . '"></span><input type="hidden" name="field3" id="field3' . $rnd1 . '" value="' . html_attr($combo_field3->SelectedData) . '">';
	$combo_field3->MatchText = '<span id="field3-container-readonly' . $rnd1 . '"></span><input type="hidden" name="field3" id="field3' . $rnd1 . '" value="' . html_attr($combo_field3->SelectedData) . '">';
	$combo_field4->HTML = '<span id="field4-container' . $rnd1 . '"></span><input type="hidden" name="field4" id="field4' . $rnd1 . '" value="' . html_attr($combo_field4->SelectedData) . '">';
	$combo_field4->MatchText = '<span id="field4-container-readonly' . $rnd1 . '"></span><input type="hidden" name="field4" id="field4' . $rnd1 . '" value="' . html_attr($combo_field4->SelectedData) . '">';
	$combo_field19->HTML = '<span id="field19-container' . $rnd1 . '"></span><input type="hidden" name="field19" id="field19' . $rnd1 . '" value="' . html_attr($combo_field19->SelectedData) . '">';
	$combo_field19->MatchText = '<span id="field19-container-readonly' . $rnd1 . '"></span><input type="hidden" name="field19" id="field19' . $rnd1 . '" value="' . html_attr($combo_field19->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_field3__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['field3'] : htmlspecialchars($filterer_field3, ENT_QUOTES)); ?>"};
		AppGini.current_field4__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['field4'] : htmlspecialchars($filterer_field4, ENT_QUOTES)); ?>"};
		AppGini.current_field19__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['field19'] : htmlspecialchars($filterer_field19, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(field3_reload__RAND__) == 'function') field3_reload__RAND__();
				if(typeof(field4_reload__RAND__) == 'function') field4_reload__RAND__();
				if(typeof(field19_reload__RAND__) == 'function') field19_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function field3_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#field3-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_field3__RAND__.value, t: 'table4', f: 'field3' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="field3"]').val(resp.results[0].id);
							$j('[id=field3-container-readonly__RAND__]').html('<span class="match-text" id="field3-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table5_view_parent]').hide(); } else { $j('.btn[id=table5_view_parent]').show(); }


							if(typeof(field3_update_autofills__RAND__) == 'function') field3_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'table4', f: 'field3' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_field3__RAND__.value = e.added.id;
				AppGini.current_field3__RAND__.text = e.added.text;
				$j('[name="field3"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table5_view_parent]').hide(); } else { $j('.btn[id=table5_view_parent]').show(); }


				if(typeof(field3_update_autofills__RAND__) == 'function') field3_update_autofills__RAND__();
			});

			if(!$j("#field3-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_field3__RAND__.value, t: 'table4', f: 'field3' },
					success: function(resp) {
						$j('[name="field3"]').val(resp.results[0].id);
						$j('[id=field3-container-readonly__RAND__]').html('<span class="match-text" id="field3-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table5_view_parent]').hide(); } else { $j('.btn[id=table5_view_parent]').show(); }

						if(typeof(field3_update_autofills__RAND__) == 'function') field3_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_field3__RAND__.value, t: 'table4', f: 'field3' },
				success: function(resp) {
					$j('[id=field3-container__RAND__], [id=field3-container-readonly__RAND__]').html('<span class="match-text" id="field3-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table5_view_parent]').hide(); } else { $j('.btn[id=table5_view_parent]').show(); }

					if(typeof(field3_update_autofills__RAND__) == 'function') field3_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function field4_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#field4-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_field4__RAND__.value, t: 'table4', f: 'field4' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="field4"]').val(resp.results[0].id);
							$j('[id=field4-container-readonly__RAND__]').html('<span class="match-text" id="field4-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table2_view_parent]').hide(); } else { $j('.btn[id=table2_view_parent]').show(); }


							if(typeof(field4_update_autofills__RAND__) == 'function') field4_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'table4', f: 'field4' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_field4__RAND__.value = e.added.id;
				AppGini.current_field4__RAND__.text = e.added.text;
				$j('[name="field4"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table2_view_parent]').hide(); } else { $j('.btn[id=table2_view_parent]').show(); }


				if(typeof(field4_update_autofills__RAND__) == 'function') field4_update_autofills__RAND__();
			});

			if(!$j("#field4-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_field4__RAND__.value, t: 'table4', f: 'field4' },
					success: function(resp) {
						$j('[name="field4"]').val(resp.results[0].id);
						$j('[id=field4-container-readonly__RAND__]').html('<span class="match-text" id="field4-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table2_view_parent]').hide(); } else { $j('.btn[id=table2_view_parent]').show(); }

						if(typeof(field4_update_autofills__RAND__) == 'function') field4_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_field4__RAND__.value, t: 'table4', f: 'field4' },
				success: function(resp) {
					$j('[id=field4-container__RAND__], [id=field4-container-readonly__RAND__]').html('<span class="match-text" id="field4-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table2_view_parent]').hide(); } else { $j('.btn[id=table2_view_parent]').show(); }

					if(typeof(field4_update_autofills__RAND__) == 'function') field4_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function field19_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#field19-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_field19__RAND__.value, t: 'table4', f: 'field19' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="field19"]').val(resp.results[0].id);
							$j('[id=field19-container-readonly__RAND__]').html('<span class="match-text" id="field19-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table3_view_parent]').hide(); } else { $j('.btn[id=table3_view_parent]').show(); }


							if(typeof(field19_update_autofills__RAND__) == 'function') field19_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'table4', f: 'field19' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_field19__RAND__.value = e.added.id;
				AppGini.current_field19__RAND__.text = e.added.text;
				$j('[name="field19"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table3_view_parent]').hide(); } else { $j('.btn[id=table3_view_parent]').show(); }


				if(typeof(field19_update_autofills__RAND__) == 'function') field19_update_autofills__RAND__();
			});

			if(!$j("#field19-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_field19__RAND__.value, t: 'table4', f: 'field19' },
					success: function(resp) {
						$j('[name="field19"]').val(resp.results[0].id);
						$j('[id=field19-container-readonly__RAND__]').html('<span class="match-text" id="field19-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table3_view_parent]').hide(); } else { $j('.btn[id=table3_view_parent]').show(); }

						if(typeof(field19_update_autofills__RAND__) == 'function') field19_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_field19__RAND__.value, t: 'table4', f: 'field19' },
				success: function(resp) {
					$j('[id=field19-container__RAND__], [id=field19-container-readonly__RAND__]').html('<span class="match-text" id="field19-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=table3_view_parent]').hide(); } else { $j('.btn[id=table3_view_parent]').show(); }

					if(typeof(field19_update_autofills__RAND__) == 'function') field19_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/table4_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/table4_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id) { // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return table4_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return table4_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return table4_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($separateDV ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#field2').replaceWith('<div class=\"form-control-static\" id=\"field2\">' + (jQuery('#field2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#field3').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#field3_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#field4').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#field4_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#field19').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#field19_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(field3)%%>', $combo_field3->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(field3)%%>', $combo_field3->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(field3)%%>', urlencode($combo_field3->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(field4)%%>', $combo_field4->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(field4)%%>', $combo_field4->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(field4)%%>', urlencode($combo_field4->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(field19)%%>', $combo_field19->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(field19)%%>', $combo_field19->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(field19)%%>', urlencode($combo_field19->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['field3' => ['table5', '&#1605;&#1604;&#1603;&#1610;&#1577; &#1575;&#1604;&#1582;&#1586;&#1610;&#1606;&#1577;'], 'field4' => ['table2', '&#1606;&#1608;&#1593; &#1575;&#1604;&#1593;&#1605;&#1604;&#1577; &#1575;&#1604;&#1605;&#1578;&#1575;&#1581;&#1577;'], 'field19' => ['table3', '&#1606;&#1608;&#1593; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577; &#1575;&#1604;&#1605;&#1578;&#1575;&#1581;'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(ID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field3)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field4)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field19)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field15)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field16)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field12)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field14)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field5)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field6)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field9)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field17)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field18)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field7)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field8)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(field10)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', safe_html($urow['ID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', html_attr($row['ID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode($urow['ID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field2)%%>', safe_html($urow['field2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field2)%%>', html_attr($row['field2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field2)%%>', urlencode($urow['field2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field3)%%>', safe_html($urow['field3']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field3)%%>', html_attr($row['field3']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field3)%%>', urlencode($urow['field3']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field4)%%>', safe_html($urow['field4']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field4)%%>', html_attr($row['field4']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field4)%%>', urlencode($urow['field4']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(field19)%%>', safe_html($urow['field19']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(field19)%%>', html_attr($row['field19']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field19)%%>', urlencode($urow['field19']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field15)%%>', safe_html($urow['field15']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field15)%%>', urlencode($urow['field15']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field16)%%>', safe_html($urow['field16']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field16)%%>', urlencode($urow['field16']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field12)%%>', safe_html($urow['field12']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field12)%%>', urlencode($urow['field12']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field14)%%>', safe_html($urow['field14']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field14)%%>', urlencode($urow['field14']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field5)%%>', safe_html($urow['field5']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field5)%%>', urlencode($urow['field5']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field6)%%>', safe_html($urow['field6']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field6)%%>', urlencode($urow['field6']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field9)%%>', safe_html($urow['field9']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field9)%%>', urlencode($urow['field9']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field17)%%>', safe_html($urow['field17']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field17)%%>', urlencode($urow['field17']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field18)%%>', safe_html($urow['field18']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field18)%%>', urlencode($urow['field18']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field7)%%>', safe_html($urow['field7']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field7)%%>', urlencode($urow['field7']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field8)%%>', safe_html($urow['field8']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field8)%%>', urlencode($urow['field8']), $templateCode);
		$templateCode = str_replace('<%%VALUE(field10)%%>', safe_html($urow['field10']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field10)%%>', urlencode($urow['field10']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(ID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field3)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field3)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field4)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field4)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field19)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field19)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field15)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field15)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field16)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field16)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field12)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field12)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field14)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field14)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field5)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field5)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field6)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field6)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field9)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field9)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field17)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field17)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field18)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field18)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field7)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field7)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field8)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field8)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(field10)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(field10)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('table4');
	if($selected_id) {
		$jdata = get_joined_record('table4', $selected_id);
		if($jdata === false) $jdata = get_defaults('table4');
		$rdata = $row;
	}
	$templateCode .= loadView('table4-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: table4_dv
	if(function_exists('table4_dv')) {
		$args=[];
		table4_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}