<?php
// This script and data application were generated by AppGini 22.12
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/table2.php');
	include_once(__DIR__ . '/table2_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('table2');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'table2';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`table2`.`id`" => "id",
		"`table2`.`field2`" => "field2",
		"`table2`.`field3`" => "field3",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`table2`.`id`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`table2`.`id`" => "id",
		"`table2`.`field2`" => "field2",
		"`table2`.`field3`" => "field3",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`table2`.`id`" => "ID",
		"`table2`.`field2`" => "&#1606;&#1608;&#1593; &#1575;&#1604;&#1593;&#1605;&#1604;&#1577;",
		"`table2`.`field3`" => "Field 3",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`table2`.`id`" => "id",
		"`table2`.`field2`" => "field2",
		"`table2`.`field3`" => "field3",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`table2` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = (getLoggedAdmin() !== false);
	$x->AllowPrintingDV = (getLoggedAdmin() !== false);
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'table2_view.php';
	$x->RedirectAfterInsert = 'table2_view.php?SelectedID=#ID#';
	$x->TableTitle = '&#1575;&#1604;&#1593;&#1605;&#1604;&#1575;&#1578;';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`table2`.`id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['ID', '&#1606;&#1608;&#1593; &#1575;&#1604;&#1593;&#1605;&#1604;&#1577;', 'Field 3', ];
	$x->ColFieldName = ['id', 'field2', 'field3', ];
	$x->ColNumber  = [1, 2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/table2_templateTV.html';
	$x->SelectedTemplate = 'templates/table2_templateTVS.html';
	$x->TemplateDV = 'templates/table2_templateDV.html';
	$x->TemplateDVP = 'templates/table2_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: table2_init
	$render = true;
	if(function_exists('table2_init')) {
		$args = [];
		$render = table2_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: table2_header
	$headerCode = '';
	if(function_exists('table2_header')) {
		$args = [];
		$headerCode = table2_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: table2_footer
	$footerCode = '';
	if(function_exists('table2_footer')) {
		$args = [];
		$footerCode = table2_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
