<?php
// This script and data application were generated by AppGini 22.12
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/table1.php');
	include_once(__DIR__ . '/table1_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('table1');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'table1';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`table1`.`ID`" => "ID",
		"if(`table1`.`field2`,date_format(`table1`.`field2`,'%Y-%m-%d'),'')" => "field2",
		"IF(    CHAR_LENGTH(`table31`.`field2`), CONCAT_WS('',   `table31`.`field2`), '') /* &#1606;&#1608;&#1593; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577; */" => "field3",
		"`table1`.`field4`" => "field4",
		"IF(    CHAR_LENGTH(`table21`.`field2`), CONCAT_WS('',   `table21`.`field2`), '') /* &#1606;&#1608;&#1593; &#1575;&#1604;&#1593;&#1605;&#1604;&#1577; */" => "field5",
		"`table1`.`field6`" => "field6",
		"`table1`.`field7`" => "field7",
		"`table1`.`field14`" => "field14",
		"`table1`.`field8`" => "field8",
		"`table1`.`field9`" => "field9",
		"IF(    CHAR_LENGTH(`table41`.`field2`), CONCAT_WS('',   `table41`.`field2`), '') /* &#1605;&#1606; &#1582;&#1586;&#1610;&#1606;&#1577; */" => "field10",
		"`table1`.`field11`" => "field11",
		"IF(    CHAR_LENGTH(`table42`.`field2`), CONCAT_WS('',   `table42`.`field2`), '') /* &#1575;&#1604;&#1610; &#1582;&#1586;&#1610;&#1606;&#1577; */" => "field12",
		"`table1`.`field13`" => "field13",
		"`table1`.`field16`" => "field16",
		"IF(    CHAR_LENGTH(`table51`.`field2`), CONCAT_WS('',   `table51`.`field2`), '') /* &#1571;&#1587;&#1605; &#1575;&#1604;&#1593;&#1605;&#1610;&#1604; */" => "field17",
		"`table1`.`field24`" => "field24",
		"`table1`.`field18`" => "field18",
		"`table1`.`field19`" => "field19",
		"`table1`.`field20`" => "field20",
		"IF(    CHAR_LENGTH(`table43`.`field2`), CONCAT_WS('',   `table43`.`field2`), '') /* &#1575;&#1604;&#1605;&#1603;&#1610;&#1606;&#1577; */" => "field21",
		"`table1`.`field25`" => "field25",
		"`table1`.`field23`" => "field23",
		"`table1`.`field22`" => "field22",
		"`table1`.`field26`" => "field26",
		"`table1`.`field29`" => "field29",
		"IF(    CHAR_LENGTH(`table44`.`field2`), CONCAT_WS('',   `table44`.`field2`), '') /* &#1605;&#1606;.&#1582;&#1586;&#1610;&#1606;&#1577; */" => "field27",
		"`table1`.`field28`" => "field28",
		"`table1`.`field15`" => "field15",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`table1`.`ID`',
		2 => '`table1`.`field2`',
		3 => '`table31`.`field2`',
		4 => 4,
		5 => '`table21`.`field2`',
		6 => 6,
		7 => '`table1`.`field7`',
		8 => '`table1`.`field14`',
		9 => '`table1`.`field8`',
		10 => '`table1`.`field9`',
		11 => '`table41`.`field2`',
		12 => 12,
		13 => '`table42`.`field2`',
		14 => 14,
		15 => 15,
		16 => '`table51`.`field2`',
		17 => 17,
		18 => '`table1`.`field18`',
		19 => '`table1`.`field19`',
		20 => '`table1`.`field20`',
		21 => '`table43`.`field2`',
		22 => 22,
		23 => '`table1`.`field23`',
		24 => '`table1`.`field22`',
		25 => '`table1`.`field26`',
		26 => 26,
		27 => '`table44`.`field2`',
		28 => 28,
		29 => 29,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`table1`.`ID`" => "ID",
		"if(`table1`.`field2`,date_format(`table1`.`field2`,'%Y-%m-%d'),'')" => "field2",
		"IF(    CHAR_LENGTH(`table31`.`field2`), CONCAT_WS('',   `table31`.`field2`), '') /* &#1606;&#1608;&#1593; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577; */" => "field3",
		"`table1`.`field4`" => "field4",
		"IF(    CHAR_LENGTH(`table21`.`field2`), CONCAT_WS('',   `table21`.`field2`), '') /* &#1606;&#1608;&#1593; &#1575;&#1604;&#1593;&#1605;&#1604;&#1577; */" => "field5",
		"`table1`.`field6`" => "field6",
		"`table1`.`field7`" => "field7",
		"`table1`.`field14`" => "field14",
		"`table1`.`field8`" => "field8",
		"`table1`.`field9`" => "field9",
		"IF(    CHAR_LENGTH(`table41`.`field2`), CONCAT_WS('',   `table41`.`field2`), '') /* &#1605;&#1606; &#1582;&#1586;&#1610;&#1606;&#1577; */" => "field10",
		"`table1`.`field11`" => "field11",
		"IF(    CHAR_LENGTH(`table42`.`field2`), CONCAT_WS('',   `table42`.`field2`), '') /* &#1575;&#1604;&#1610; &#1582;&#1586;&#1610;&#1606;&#1577; */" => "field12",
		"`table1`.`field13`" => "field13",
		"`table1`.`field16`" => "field16",
		"IF(    CHAR_LENGTH(`table51`.`field2`), CONCAT_WS('',   `table51`.`field2`), '') /* &#1571;&#1587;&#1605; &#1575;&#1604;&#1593;&#1605;&#1610;&#1604; */" => "field17",
		"`table1`.`field24`" => "field24",
		"`table1`.`field18`" => "field18",
		"`table1`.`field19`" => "field19",
		"`table1`.`field20`" => "field20",
		"IF(    CHAR_LENGTH(`table43`.`field2`), CONCAT_WS('',   `table43`.`field2`), '') /* &#1575;&#1604;&#1605;&#1603;&#1610;&#1606;&#1577; */" => "field21",
		"`table1`.`field25`" => "field25",
		"`table1`.`field23`" => "field23",
		"`table1`.`field22`" => "field22",
		"`table1`.`field26`" => "field26",
		"`table1`.`field29`" => "field29",
		"IF(    CHAR_LENGTH(`table44`.`field2`), CONCAT_WS('',   `table44`.`field2`), '') /* &#1605;&#1606;.&#1582;&#1586;&#1610;&#1606;&#1577; */" => "field27",
		"`table1`.`field28`" => "field28",
		"`table1`.`field15`" => "field15",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`table1`.`ID`" => "ID",
		"`table1`.`field2`" => "&#1578;&#1575;&#1585;&#1610;&#1582; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577;",
		"IF(    CHAR_LENGTH(`table31`.`field2`), CONCAT_WS('',   `table31`.`field2`), '') /* &#1606;&#1608;&#1593; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577; */" => "&#1606;&#1608;&#1593; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577;",
		"`table1`.`field4`" => "&#1606;&#1608;&#1593; - &#1575;&#1604;&#1581;&#1585;&#1603;&#1577;",
		"IF(    CHAR_LENGTH(`table21`.`field2`), CONCAT_WS('',   `table21`.`field2`), '') /* &#1606;&#1608;&#1593; &#1575;&#1604;&#1593;&#1605;&#1604;&#1577; */" => "&#1606;&#1608;&#1593; &#1575;&#1604;&#1593;&#1605;&#1604;&#1577;",
		"`table1`.`field6`" => "&#1606;&#1608;&#1593; - &#1575;&#1604;&#1593;&#1605;&#1604;&#1577;",
		"`table1`.`field7`" => "&#1602;&#1610;&#1605;&#1577;",
		"`table1`.`field14`" => "&#1575;&#1604;&#1602;&#1610;&#1605;&#1577;",
		"`table1`.`field8`" => "&#1587;&#1593;&#1585; &#1575;&#1604;&#1589;&#1585;&#1601;",
		"`table1`.`field9`" => "&#1575;&#1604;&#1575;&#1580;&#1605;&#1575;&#1604;&#1610;",
		"IF(    CHAR_LENGTH(`table41`.`field2`), CONCAT_WS('',   `table41`.`field2`), '') /* &#1605;&#1606; &#1582;&#1586;&#1610;&#1606;&#1577; */" => "&#1605;&#1606; &#1582;&#1586;&#1610;&#1606;&#1577;",
		"`table1`.`field11`" => "&#1605;&#1606; - &#1582;&#1586;&#1610;&#1606;&#1577;",
		"IF(    CHAR_LENGTH(`table42`.`field2`), CONCAT_WS('',   `table42`.`field2`), '') /* &#1575;&#1604;&#1610; &#1582;&#1586;&#1610;&#1606;&#1577; */" => "&#1575;&#1604;&#1610; &#1582;&#1586;&#1610;&#1606;&#1577;",
		"`table1`.`field13`" => "&#1575;&#1604;&#1610; - &#1582;&#1586;&#1610;&#1606;&#1577;",
		"`table1`.`field16`" => "&#1585;&#1602;&#1605; &#1575;&#1604;&#1576;&#1591;&#1575;&#1602;&#1577;",
		"IF(    CHAR_LENGTH(`table51`.`field2`), CONCAT_WS('',   `table51`.`field2`), '') /* &#1571;&#1587;&#1605; &#1575;&#1604;&#1593;&#1605;&#1610;&#1604; */" => "&#1571;&#1587;&#1605; &#1575;&#1604;&#1593;&#1605;&#1610;&#1604;",
		"`table1`.`field24`" => "&#1575;&#1604;&#1593;&#1605;&#1610;&#1604;",
		"`table1`.`field18`" => "&#1575;&#1604;&#1602;&#1610;&#1605;&#1577; &#1575;&#1604;&#1605;&#1587;&#1581;&#1608;&#1576;&#1577;",
		"`table1`.`field19`" => "&#1593;&#1605;&#1608;&#1604;&#1577; &#1575;&#1604;&#1587;&#1581;&#1576;",
		"`table1`.`field20`" => "&#1585;&#1589;&#1610;&#1583; &#1605;&#1578;&#1575;&#1581;",
		"IF(    CHAR_LENGTH(`table43`.`field2`), CONCAT_WS('',   `table43`.`field2`), '') /* &#1575;&#1604;&#1605;&#1603;&#1610;&#1606;&#1577; */" => "&#1575;&#1604;&#1605;&#1603;&#1610;&#1606;&#1577;",
		"`table1`.`field25`" => "&#1605;&#1603;&#1610;&#1606;&#1577; &#1575;&#1604;&#1587;&#1581;&#1576;",
		"`table1`.`field23`" => "&#1593;&#1605;&#1608;&#1604;&#1577; &#1575;&#1604;&#1605;&#1581;&#1604;",
		"`table1`.`field22`" => "&#1583;&#1582;&#1608;&#1604; &#1605;&#1603;&#1610;&#1606;&#1577;",
		"`table1`.`field26`" => "&#1578;&#1587;&#1604;&#1610;&#1605; &#1602; &#1573;&#1588;&#1575;&#1585;&#1610;",
		"`table1`.`field29`" => "&#1585;&#1602;&#1605; &#1573;&#1588;&#1575;&#1585;&#1610;",
		"IF(    CHAR_LENGTH(`table44`.`field2`), CONCAT_WS('',   `table44`.`field2`), '') /* &#1605;&#1606;.&#1582;&#1586;&#1610;&#1606;&#1577; */" => "&#1605;&#1606;.&#1582;&#1586;&#1610;&#1606;&#1577;",
		"`table1`.`field28`" => "&#1605;&#1606;..&#1582;&#1586;&#1610;&#1606;&#1577;",
		"`table1`.`field15`" => "&#1605;&#1604;&#1575;&#1581;&#1592;&#1577; &#1593;&#1606; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577;",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`table1`.`ID`" => "ID",
		"if(`table1`.`field2`,date_format(`table1`.`field2`,'%Y-%m-%d'),'')" => "field2",
		"IF(    CHAR_LENGTH(`table31`.`field2`), CONCAT_WS('',   `table31`.`field2`), '') /* &#1606;&#1608;&#1593; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577; */" => "field3",
		"`table1`.`field4`" => "field4",
		"IF(    CHAR_LENGTH(`table21`.`field2`), CONCAT_WS('',   `table21`.`field2`), '') /* &#1606;&#1608;&#1593; &#1575;&#1604;&#1593;&#1605;&#1604;&#1577; */" => "field5",
		"`table1`.`field6`" => "field6",
		"`table1`.`field7`" => "field7",
		"`table1`.`field14`" => "field14",
		"`table1`.`field8`" => "field8",
		"`table1`.`field9`" => "field9",
		"IF(    CHAR_LENGTH(`table41`.`field2`), CONCAT_WS('',   `table41`.`field2`), '') /* &#1605;&#1606; &#1582;&#1586;&#1610;&#1606;&#1577; */" => "field10",
		"`table1`.`field11`" => "field11",
		"IF(    CHAR_LENGTH(`table42`.`field2`), CONCAT_WS('',   `table42`.`field2`), '') /* &#1575;&#1604;&#1610; &#1582;&#1586;&#1610;&#1606;&#1577; */" => "field12",
		"`table1`.`field13`" => "field13",
		"`table1`.`field16`" => "field16",
		"IF(    CHAR_LENGTH(`table51`.`field2`), CONCAT_WS('',   `table51`.`field2`), '') /* &#1571;&#1587;&#1605; &#1575;&#1604;&#1593;&#1605;&#1610;&#1604; */" => "field17",
		"`table1`.`field24`" => "field24",
		"`table1`.`field18`" => "field18",
		"`table1`.`field19`" => "field19",
		"`table1`.`field20`" => "field20",
		"IF(    CHAR_LENGTH(`table43`.`field2`), CONCAT_WS('',   `table43`.`field2`), '') /* &#1575;&#1604;&#1605;&#1603;&#1610;&#1606;&#1577; */" => "field21",
		"`table1`.`field25`" => "field25",
		"`table1`.`field23`" => "field23",
		"`table1`.`field22`" => "field22",
		"`table1`.`field26`" => "field26",
		"`table1`.`field29`" => "field29",
		"IF(    CHAR_LENGTH(`table44`.`field2`), CONCAT_WS('',   `table44`.`field2`), '') /* &#1605;&#1606;.&#1582;&#1586;&#1610;&#1606;&#1577; */" => "field27",
		"`table1`.`field28`" => "field28",
		"`table1`.`field15`" => "field15",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['field3' => '&#1606;&#1608;&#1593; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577;', 'field5' => '&#1606;&#1608;&#1593; &#1575;&#1604;&#1593;&#1605;&#1604;&#1577;', 'field10' => '&#1605;&#1606; &#1582;&#1586;&#1610;&#1606;&#1577;', 'field12' => '&#1575;&#1604;&#1610; &#1582;&#1586;&#1610;&#1606;&#1577;', 'field17' => '&#1571;&#1587;&#1605; &#1575;&#1604;&#1593;&#1605;&#1610;&#1604;', 'field21' => '&#1575;&#1604;&#1605;&#1603;&#1610;&#1606;&#1577;', 'field27' => '&#1605;&#1606;.&#1582;&#1586;&#1610;&#1606;&#1577;', ];

	$x->QueryFrom = "`table1` LEFT JOIN `table3` as table31 ON `table31`.`id`=`table1`.`field3` LEFT JOIN `table2` as table21 ON `table21`.`id`=`table1`.`field5` LEFT JOIN `table4` as table41 ON `table41`.`ID`=`table1`.`field10` LEFT JOIN `table4` as table42 ON `table42`.`ID`=`table1`.`field12` LEFT JOIN `table5` as table51 ON `table51`.`ID`=`table1`.`field17` LEFT JOIN `table4` as table43 ON `table43`.`ID`=`table1`.`field21` LEFT JOIN `table4` as table44 ON `table44`.`ID`=`table1`.`field27` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 0;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = (getLoggedAdmin() !== false);
	$x->AllowPrintingDV = (getLoggedAdmin() !== false);
	$x->AllowCSV = (getLoggedAdmin() !== false);
	$x->RecordsPerPage = 2000;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'table1_view.php';
	$x->RedirectAfterInsert = 'table1_view.php?SelectedID=#ID#';
	$x->TableTitle = '&#1575;&#1604;&#1581;&#1585;&#1603;&#1577; &#1575;&#1604;&#1610;&#1608;&#1605;&#1610;&#1577;';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`table1`.`ID`';
	$x->DefaultSortField = '`table1`.`field2`';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', '&#1578;&#1575;&#1585;&#1610;&#1582; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577;', '&#1606;&#1608;&#1593; - &#1575;&#1604;&#1581;&#1585;&#1603;&#1577;', '&#1606;&#1608;&#1593; - &#1575;&#1604;&#1593;&#1605;&#1604;&#1577;', '&#1575;&#1604;&#1602;&#1610;&#1605;&#1577;', '&#1587;&#1593;&#1585; &#1575;&#1604;&#1589;&#1585;&#1601;', '&#1575;&#1604;&#1575;&#1580;&#1605;&#1575;&#1604;&#1610;', '&#1605;&#1606; - &#1582;&#1586;&#1610;&#1606;&#1577;', '&#1575;&#1604;&#1610; - &#1582;&#1586;&#1610;&#1606;&#1577;', '&#1585;&#1602;&#1605; &#1575;&#1604;&#1576;&#1591;&#1575;&#1602;&#1577;', '&#1575;&#1604;&#1593;&#1605;&#1610;&#1604;', '&#1575;&#1604;&#1602;&#1610;&#1605;&#1577; &#1575;&#1604;&#1605;&#1587;&#1581;&#1608;&#1576;&#1577;', '&#1593;&#1605;&#1608;&#1604;&#1577; &#1575;&#1604;&#1587;&#1581;&#1576;', '&#1585;&#1589;&#1610;&#1583; &#1605;&#1578;&#1575;&#1581;', '&#1605;&#1603;&#1610;&#1606;&#1577; &#1575;&#1604;&#1587;&#1581;&#1576;', '&#1578;&#1587;&#1604;&#1610;&#1605; &#1602; &#1573;&#1588;&#1575;&#1585;&#1610;', '&#1585;&#1602;&#1605; &#1573;&#1588;&#1575;&#1585;&#1610;', '&#1605;&#1606;.&#1582;&#1586;&#1610;&#1606;&#1577;', '&#1605;&#1604;&#1575;&#1581;&#1592;&#1577; &#1593;&#1606; &#1575;&#1604;&#1581;&#1585;&#1603;&#1577;', ];
	$x->ColFieldName = ['ID', 'field2', 'field4', 'field6', 'field14', 'field8', 'field9', 'field11', 'field13', 'field16', 'field24', 'field18', 'field19', 'field20', 'field25', 'field26', 'field29', 'field27', 'field15', ];
	$x->ColNumber  = [1, 2, 4, 6, 8, 9, 10, 12, 14, 15, 17, 18, 19, 20, 22, 25, 26, 27, 29, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/table1_templateTV.html';
	$x->SelectedTemplate = 'templates/table1_templateTVS.html';
	$x->TemplateDV = 'templates/table1_templateDV.html';
	$x->TemplateDVP = 'templates/table1_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: table1_init
	$render = true;
	if(function_exists('table1_init')) {
		$args = [];
		$render = table1_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')) {
		// if printing multi-selection TV, calculate the sum only for the selected records
		$record_selector = Request::val('record_selector');
		if(Request::val('Print_x') && is_array($record_selector)) {
			$QueryWhere = '';
			foreach($record_selector as $id) {   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != '') {
				$QueryWhere = 'where `table1`.`ID` in ('.substr($QueryWhere, 0, -1).')';
			} else { // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		} else {
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery = "SELECT SUM(`table1`.`field14`), SUM(`table1`.`field9`), SUM(`table1`.`field18`), SUM(`table1`.`field20`), SUM(`table1`.`field26`) FROM {$x->QueryFrom} {$QueryWhere}";
		$res = sql($sumQuery, $eo);
		if($row = db_fetch_row($res)) {
			$sumRow = '<tr class="success sum">';
			if(!Request::val('Print_x')) $sumRow .= '<th class="text-center sum">&sum;</th>';
			$sumRow .= '<td class="table1-ID sum"></td>';
			$sumRow .= '<td class="table1-field2 sum"></td>';
			$sumRow .= '<td class="table1-field4 sum"></td>';
			$sumRow .= '<td class="table1-field6 sum"></td>';
			$sumRow .= "<td class=\"table1-field14 text-right sum locale-float\">{$row[0]}</td>";
			$sumRow .= '<td class="table1-field8 sum"></td>';
			$sumRow .= "<td class=\"table1-field9 text-left sum locale-float\">{$row[1]}</td>";
			$sumRow .= '<td class="table1-field11 sum"></td>';
			$sumRow .= '<td class="table1-field13 sum"></td>';
			$sumRow .= '<td class="table1-field16 sum"></td>';
			$sumRow .= '<td class="table1-field24 sum"></td>';
			$sumRow .= "<td class=\"table1-field18 text-right sum locale-float\">{$row[2]}</td>";
			$sumRow .= '<td class="table1-field19 sum"></td>';
			$sumRow .= "<td class=\"table1-field20 text-right sum locale-float\">{$row[3]}</td>";
			$sumRow .= '<td class="table1-field25 sum"></td>';
			$sumRow .= "<td class=\"table1-field26 text-right sum locale-float\">{$row[4]}</td>";
			$sumRow .= '<td class="table1-field29 sum"></td>';
			$sumRow .= '<td class="table1-field27 sum"></td>';
			$sumRow .= '<td class="table1-field15 sum"></td>';
			$sumRow .= '</tr>';

			$x->HTML = str_replace('<!-- tv data below -->', '', $x->HTML);
			$x->HTML = str_replace('<!-- tv data above -->', $sumRow, $x->HTML);
		}
	}

	// hook: table1_header
	$headerCode = '';
	if(function_exists('table1_header')) {
		$args = [];
		$headerCode = table1_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: table1_footer
	$footerCode = '';
	if(function_exists('table1_footer')) {
		$args = [];
		$footerCode = table1_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
